calculate:
  - ellipsoid
  - full
calculate_every: 10
sampled_classes: 10
examples_per_class: 128
return_nodes:
- conv1
- layer1.0.conv1
- layer1.0.conv2
- layer1.1.conv1
- layer1.1.conv2
- layer2.0.conv1
- layer2.0.conv2
- layer2.1.conv1
- layer2.1.conv2
- layer3.0.conv1
- layer3.0.conv2
- layer3.1.conv1
- layer3.1.conv2
- layer4.0.conv1
- layer4.0.conv2
- layer4.1.conv1
- layer4.1.conv2
dataset_kwargs:
  root:  ${oc.env:EXPERIMENT_ROOT}/data
  train: true
  download: true
dataset: "mnist"
