encoder:
  type: resnet18
  weights: null
  kwargs:
    pretrained: false
    in_chans: 1
    num_classes: 0
    global_pool: ''

classification_type: linear
classification_kwargs: 
  in_features: 2048
  out_features: 10

autoregresssive_type: lstm
autoregresssive_kwargs:
  input_size: 2048
  hidden_size: 2048
  num_layers: 1
