defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - dataset: moving_mnist
  - manifold: default

batch_size: 32
learning_rate: 0.001
epochs: 100


hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: sphere
    storage: null
    n_trials: 20
    n_jobs: 1
    max_failure_rate: 0.0
    params:
      x: range(-5.5, 5.5, step=0.5)
      y: choice(-5 ,0 ,5)

x: 1
y: 1
z: 1

# if true, simulate a failure by raising an exception
error: false