type: default
encoder:
  type: resnet18
  weights: null
  kwargs:
    pretrained: false
    in_chans: 1
    num_classes: 0
    global_pool: ''

classification_type: null
classification_kwargs: {}

autoregressive_type: lstm
autoregressive_kwargs:
  input_size: 2048
  hidden_size: 2048
  num_layers: 1

projection_kwargs: null

name: lstm